### PR TITLE
Upgrade CI runner from macos-12 to macos-13

### PR DESCRIPTION
**Pull request by qmuntal**
MacOS CI runners are deprecated and will be removed soon: https://github.com/actions/runner-images/issues/10721.

In fact, macOS already entered the burnout period.

### CODE REVIEW

**Review by gdams — APPROVED** [review]

**Comment by qmuntal** [comment]
Grr, `libcrypto.3.dylib` does not exist in macos-14 (nor 13, nor 15...). In fact, the GH runner documentation says that those newer macOS images only ship with OpenSSL 1.1.1. OpenSSL 3 was probably included in macos-12 by mistake.

The problem is that there doesn't seem to be a `libcrypto1.1.dylib` file neither...

Maybe because just today macOS is migrating to OpenSSL 3 (https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md) and things a bit messy. Will wait till tomorrow.

**Comment by dagood** [comment]
According to https://github.com/actions/runner-images/issues/10817 macOS 13 will get OpenSSL 3, so I suppose we should end up pointing at that (rather than 14) to get oldest possible coverage?

**Comment by gdams** [comment]
Can we not `brew install openssl@3`?

**Comment by gdams** [comment]
> According to [actions/runner-images#10817](https://github.com/actions/runner-images/issues/10817) macOS 13 will get OpenSSL 3, so I suppose we should end up pointing at that (rather than 14) to get oldest possible coverage?

actually yeah we may as well wait. Apparently "Image deployment will start on November 4 and will take 2-3 days."

**Comment by qmuntal** [comment]
Finally found the right path to `libcrypto.3.dylib` 😅.

**Comment by qmuntal** [comment]
@dagood PTAL

**Review by dagood — APPROVED** [review]

**Pull request merged**
